### ISSUE TITLE
CSS Not Rendering

### ISSUE THREAD

**Issue by haganbt** [marcgarreau/accelerator#13]
When running the development server, no css assets are rendered and the page is broken as a result i.e. the react-md assets.

When I run the production build, no css assets are produced within the ```/build``` dir.

Any thoughts or guidance on how to fix this would be appreciated.

**Comment by wolovim** [comment]
You may have skipped this step in the README:
`Set up your environment variables file: cp .env.example .env`

**Comment by haganbt** [comment]
Ah yes that was it! Many thanks.
